description: >
  Hello, I'm **Thomas Parisot**, a frenchman with web development, collaborative work and user experience skills.
author: Thomas Parisot
email: hi@thom4.net
disqus_shortname: thom4parisot

graph:
  twitter:        thom4parisot
  mastodon:       https://masto.oncletom.io/@thomas
webmentions:
  url: https://webmention.io/thom4.net
  features:
    pingback:   xmlrpc
    webmention: webmention

summary:
  home: |
    Hello and welcome to my online&nbsp;space.
    Here, I explore a way to document my journey through life.

    _Enjoy!_ — Thomas
  work: >
    I combine web development, UX research and human-centered agile practices
    to put people at ease, to create a shared understanding of the _whys_ and the _whats_
    and to move from ideas to prototyping then to production.

links:
  - label: Writings
    href: /
  - label: Livre Node.js
    href: /node.js/
    lang: fr
  - label: Presentations
    href: /talks/
  - label: Reading Notes
    href: /reading-notes/
  - label: Photography
    href: /photography/
  - label: Hire me
    href: https://détour.studio
  - label: About
    href: /about/

less:
  layouts:
    series-day-to-day:
      - styles/series-day-to-day.css
    series-default:
      - styles/series-default.css
  paths:
    - source/less
    - node_modules/bootstrap/less
    - node_modules/hexo-theme-thom4/source/less
    - node_modules/hexo-theme-thom4/node_modules
    - node_modules
